name: Sample 2 workflow

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: heartbeat pulse
        run: echo "sample_2 workflow heartbeat"
        shell: bash
  test-python-code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
      - uses: actions/checkout@v2

      - name: setup python
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: run pthon script
        run: |
          python -m pip install requests
          python samplescript.py

  
